### PR TITLE
Update to Crystal 0.21.0

### PR DESCRIPTION
**Pull request by thomasnal**
Everybody can enjoy compiled Rails like web-application framework.

### CODE REVIEW

**Comment by Codcore** [comment]
Please, make TravisCI build to pass.

**Comment by thomasnal** [comment]
Sure.  Github automatically created PR in your repo that was premature.

Although code works, I have seen the tests have some trouble to run. `crystal deps` starts a listening http server for some reason.  And now I see travis has trouble finding `html_builder`.  Need a couple days to find time to fix that.  Bear with me.

**Comment by thomasnal** [comment]
I appreciate your response.  Haven't seen you active in 2016.  Cudos for a quite nice architecture and clean code.  Did you get inspiration for the architecture from Rails or just from top of the head?

Why have you stopped the project in the past - other interests/lack of time or technical challenges you foresaw?

**Comment by bararchy** [comment]
@Codcore ! Long time now seen :) 
Are we back in business ? ;)

**Comment by Codcore** [comment]
@thomasnal, thank you. Yes, I was inspired by the Rails))) Oh, there are many reasons why I stopped this project =)

@bararchy, hello, my friend! Nice to see you XD. I'm not sure if I will come back.

**Comment by Codcore** [comment]
@thomasnal fine, good job!

**Pull request merged**
