### PR TITLE
Use HTML::Builder for creating view helpers

### PR DESCRIPTION
**Pull request by davydovanton**

### CODE REVIEW

**Comment by bararchy** [comment]
Nice one @davydovanton Thanks.

**Comment by davydovanton** [comment]
Also I updated `HTML::Builder` class (https://github.com/manastech/crystal/pull/1031) and in the next version of crystal I will update `ViewHelper` too :smiley:

**Comment by bararchy** [comment]
@davydovanton If you want to test and update using Crystal\HEAD, we have a branch just for that :) 
https://github.com/Codcore/amethyst/tree/crystal-head

**Comment by davydovanton** [comment]
@bararchy cool, i will check this later, thanks!

**Comment by Codcore** [comment]
Good work!

**Comment by davydovanton** [comment]
@Codcore thanks! :tada:

**Pull request merged**
