### PR TITLE
Added shards support

### PR DESCRIPTION
**Pull request by sdogruyol**
As of Crystal 0.8.0 shards is the default dependency manager.

### CODE REVIEW

**Comment by davidpatters0n** [comment]
:100: for Crystal 0.8.0 support.

**Comment by pine** [comment]
:+1:

**Comment by sdogruyol** [comment]
The latest commit make Amethyst work with 0.8.0 all specs passing :+1:

**Comment by sdogruyol** [comment]
Meanwhile i don't know why Travis is failing :dart:

**Comment by ahmetabdi** [comment]
:+1:

**Comment by davidpatters0n** [comment]
@sdogruyol according to the travis report. It fails when executing `crystal deps` the shards dependency manager needs to be installed first.

**Comment by sdogruyol** [comment]
Ah currently shards is an external executable. How can we make travis happy for this?

**Comment by Codcore** [comment]
@sdogruyol, my PC is currently broken, but I think  Travis.yml should be edited to download and install shards manually first

**Comment by sdogruyol** [comment]
Thanks @Codcore i'll look into that :)

**Comment by sdogruyol** [comment]
Thanks to @jhass the build passed :+1: 

Can you merge this @Codcore

**Comment by Codcore** [comment]
@sdogruyol Nice job, thanks!!!

**Comment by sdogruyol** [comment]
:+1:

**Pull request merged**
